"""Phase 6 Dreams — add communication_mode to episodic_memories (Phase A'' retroactive).

Revision ID: 003
Revises: 002
Create Date: 2026-04-14

Adds the nullable communication_mode column to episodic_memories so
Alicia-away memories generated by Dreams carry phone/letter/video_call
tags. Layer-5 filtering in layers.py:75-84 honors this tag on read.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "003"
down_revision: str | None = "002"
branch_labels: tuple[str, ...] | None = None
depends_on: str | None = None

SCHEMA = "starry_lyfe"


def upgrade() -> None:
    op.add_column(
        "episodic_memories",
        sa.Column("communication_mode", sa.String(20), nullable=True),
        schema=SCHEMA,
    )


def downgrade() -> None:
    op.drop_column("episodic_memories", "communication_mode", schema=SCHEMA)
