"""Phase K: Flattening Regression Detector.

Scans assembled prompt sample files for cross-character vocabulary overlap
and per-character canonical marker presence. Outputs a report to
Docs/flattening_dashboard.md.

Run weekly or after any significant code change:
    python scripts/flattening_regression_detector.py

Exit codes:
    0 — all checks pass, no flattening detected
    1 — overlap or missing-marker warning (investigate before shipping)
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Canonical markers that must appear in each character's assembled prompt.
# Absence signals that a canonical register was dropped.
REQUIRED_MARKERS: dict[str, list[str]] = {
    "adelia": [
        "Entangled Pair", "Marrickville", "Las Fallas", "Ozone",
        "Whiteboard Mode", "Bunker Mode", "1+1=11",
    ],
    "bina": [
        "Circuit Pair", "Urmia", "samovar", "Gilgamesh",
        "Arash", "Farhad",
    ],
    "reina": [
        "Kinetic Pair", "Gracia", "Cuatrecasas", "Bishop",
        "Admissibility Protocol", "Mastermind",
    ],
    "alicia": [
        "Solstice Pair", "Famaill", "Canciller", "Sun Override",
        "Complete Jungian Duality",
        # Mercedes Sosa is in rioplatense/famailla knowledge cards (scene-conditional)
        # and verified by J.4 regression tests — not in all scene types' assembled prompts
    ],
}

# Markers that are exclusive to one character.
# Presence in another character's prompt is a contamination failure.
EXCLUSIVE_MARKERS: dict[str, list[str]] = {
    "adelia": ["Marrickville", "Las Fallas", "Ozone and Ember"],
    "bina":   ["samovar", "Urmia", "Circuit Pair"],
    "reina":  ["Cuatrecasas", "Kinetic Pair"],
    "alicia": ["Famaill", "Canciller", "Solstice Pair"],
}


def _find_latest_sample(char: str) -> Path | None:
    """Find the most recently dated assembled sample for a character."""
    samples_dir = PROJECT_ROOT / "Docs" / "_phases" / "_samples"
    candidates = sorted(samples_dir.glob(f"*assembled_{char}*.txt"), reverse=True)
    return candidates[0] if candidates else None


def _check_character(char: str, sample_path: Path) -> list[str]:
    """Return list of warning strings for a character's sample file."""
    warnings: list[str] = []
    text = sample_path.read_text(encoding="utf-8", errors="replace")

    # Required marker presence
    for marker in REQUIRED_MARKERS.get(char, []):
        if marker.lower() not in text.lower():
            warnings.append(f"  MISSING required marker '{marker}' in {char} sample")

    # Cross-character contamination
    for other_char, markers in EXCLUSIVE_MARKERS.items():
        if other_char == char:
            continue
        for marker in markers:
            if marker.lower() in text.lower():
                warnings.append(
                    f"  CONTAMINATION: '{marker}' ({other_char}-exclusive) "
                    f"found in {char} sample"
                )

    return warnings


def _build_report(results: dict[str, list[str]]) -> str:
    lines = ["# Flattening Regression Dashboard\n"]
    all_clean = all(not w for w in results.values())

    lines.append(f"**Status:** {'✅ CLEAN' if all_clean else '⚠️  WARNINGS DETECTED'}\n")

    for char, warnings in results.items():
        status = "✅" if not warnings else "⚠️"
        lines.append(f"\n## {status} {char.title()}\n")
        if warnings:
            for w in warnings:
                lines.append(f"- {w.strip()}")
        else:
            lines.append("All required markers present. No contamination detected.")

    lines.append("\n---")
    lines.append("\n*Generated by `scripts/flattening_regression_detector.py`.*")
    lines.append("*Run weekly or after any significant code change.*")
    return "\n".join(lines)


def main() -> int:
    results: dict[str, list[str]] = {}
    chars = ["adelia", "bina", "reina", "alicia"]

    for char in chars:
        sample = _find_latest_sample(char)
        if sample is None:
            results[char] = [f"  NO SAMPLE FILE found for {char}"]
            continue
        print(f"Scanning {char}: {sample.name}")
        results[char] = _check_character(char, sample)

    # Write dashboard
    dashboard_path = PROJECT_ROOT / "Docs" / "flattening_dashboard.md"
    dashboard_path.write_text(_build_report(results), encoding="utf-8")
    print(f"\nDashboard written to: {dashboard_path}")

    # Print summary
    total_warnings = sum(len(w) for w in results.values())
    if total_warnings:
        print(f"\nWARNING: {total_warnings} warning(s) detected -- review before shipping.")
        for _char, warnings in results.items():
            for w in warnings:
                print(w)
        return 1

    print("\nOK: All characters clean -- no flattening detected.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
